### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dadang223** [raulhaag/gean#1]
how to use sir

**Comment by raulhaag** [comment]
For the moment still in development, you can try but the content is only in spanish.
You need to have installed python and run httpServer.py, and if the browser don't open go to in your browser yo http://127.0.0.1:8080/main.html if you don't see the main page go to the config(gear top right) and disable "Bloquear pagina principal" then click back (< top left).
The source server can be changed from top center menu. 
There is a second version not fully functional but you can test it in http://127.0.0.1:8080/main_2.html (only keyboard navigation: up, down, left, right and enter)
